# fly.toml app configuration file generated for fly-tailscale-metrics on 2023-12-17T20:13:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-tailscale-metrics"
primary_region = "lhr"

[build]

[[services]] ## https://fly.io/docs/reference/configuration/#:~:text=app%20can%20have%3A-,No%20services%20section,-(and%20no%20http_service

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 9091
  path = "/metrics"

